Update Import.php
philwinkle/Philwinkle_Fixerio pull request #20
Opened 2018-03-30 21:48 UTC by btekbtek

Update API request with Access Key and new URL.
To get this work please change Access Key in code to your access key from fixier.io account.

2018-03-31 12:44 UTC, sreichel commented
I think API key should be set in admin config section.

2018-04-04 08:16 UTC, btekbtek commented
Yes I know but I'm testing only now. Should be something like this:

I found that free plan only work for base currency -  EUR so I'm not sure we continue with this.

2018-04-04 08:37 UTC, btekbtek commented
There is also free https://free.currencyconverterapi.com/api/v5/convert?q=GBP_PHP,PHP_AUD&compact=ultra 

But I have problem make this work

2018-04-04 16:17 UTC, philwinkle commented on app/code/community/Philwinkle/Fixerio/Model/Import.php
> +    protected $_url = 'https://data.fixer.io/api/latest?access_key=YOUR_ACCESS_KEY&base=%1$s&symbols=%2$s';
ACCESS_KEY needs to be an admin-configurable setting or have a valid fallback value. This should be store configuration-scoped. Please provide a setup script for that and we'll get this merged! Thanks!

2018-04-04 16:17 UTC, philwinkle requested changes
Thanks! Few updates.

2018-04-12 00:37 UTC, philwinkle commented
@btekbtek please resubmit once `ACCESS_KEY` is admin-configurable. Thanks!

2018-04-12 00:37 UTC, closed without merging